# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9fd0c9ec94225c8acc663e02b4640a237ddd84b1e13040935cac245008ab4d91e3eb106b7002cf6a6c5930b20b183324f52bf8ffc4da35b350b8256d346073c

test:
  secret_key_base: 934dc7ccaa34c3a7ae15f34261f473ba9e86ad2e82cd8febdcc552b9f5a890fa9cd1753394db264210ea233e9f7d9f226ba09bc48aaef6a77c7461cbf562cdf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
